#!/bin/bash

echo "Running on Ubuntu 24.04"

sudo apt update -y

sudo apt install nginx -y
if [ $? -ne 0 ]; then
    echo "ERROR:: Installing nginx failed"
    exit 1
else
    echo "Installing nginx SUCCESS"
fi

