#!/bin/bash

sudo apt update -y

sudo apt install nginx -y
if [ $? -ne 0 ]; then
    echo "ERROR:: Installing nginx failed"
    exit 1
else
    echo "Installing nginx SUCCESS"
fi

sudo apt install mongodb-mongosh -y
if [ $? -ne 0 ]; then
    echo "ERROR:: Installing mongodb-mongosh failed"
    exit 1
else
    echo "Installing mongodb-mongosh SUCCESS"
fi

