#!/bin/bash

USERID=$(ID -u)

if [ $USERID -ne 0 ]: then
     echo "ERROR:: please run this cript with root privelege"
     exit 1 # failure is other than 0
fi     

apt install mysql -y 

if [ $? -ne 0 ]; then 
    echo "ERROR:: Installing MySQL is failure"
    exit 1
else 
    echo "installing mysql is susses"
fi


